/*Version 23.07 Script to create "FrameData" database schema for SQLite*/

/*Create all tables*/
CREATE TABLE Unit (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    ua_number VARCHAR(15) NOT NULL UNIQUE,
    width REAL NOT NULL DEFAULT 0
);

CREATE TABLE Pane (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    unit_id INTEGER NOT NULL,
    pane_number TINYINT NOT NULL,
    plunge_depth REAL NOT NULL DEFAULT 0,
    FOREIGN KEY (unit_id) REFERENCES Unit(id)
);

CREATE TABLE Edge (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    pane_id INTEGER NOT NULL,
    edge_number TINYINT NOT NULL,
    edge_type TINYINT NOT NULL DEFAULT 0,
    fill_area REAL NOT NULL DEFAULT 0,
    x0 REAL NOT NULL DEFAULT 0,
    y0 REAL NOT NULL DEFAULT 0,
    z0 REAL NOT NULL DEFAULT 0,
    x1 REAL NOT NULL DEFAULT 0,
    y1 REAL NOT NULL DEFAULT 0,
    z1 REAL NOT NULL DEFAULT 0,
    FOREIGN KEY (pane_id) REFERENCES Pane(id)
);

CREATE TABLE Obstruction (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    edge_id INTEGER NOT NULL,
	obstruction_number TINYINY NOT NULL DEFAULT 1,
	search_type TINYINT NOT NULL DEFAULT 0,
	track_type TINYINT NOT NULL DEFAULT 0,
	offset REAL NOT NULL DEFAULT 0,
	width REAL NOT NULL DEFAULT 0,
    FOREIGN KEY (edge_id) REFERENCES Edge(id)
);